### ISSUE TITLE
Installing AnyDSL projects

### ISSUE THREAD

**Issue by ib00** [AnyDSL/anydsl#12]
What's the preferred way of installing various AnyDSL projects?

I have built everything, but I am not sure what's the best way of
installing include files and libraries other than manually copying  
everything.

**Comment by madmann91** [comment]
We normally build our projects with CMake. The [anydsl meta-repository](https://github.com/AnyDSL/anydsl) automates this process. We don't have to copy files and libraries since the CMake logic of the runtime allows to directly use the `build` directory of each project.

**Comment by ib00** [comment]
Thank you. 

It's a bit hard to do some quick prototyping. For example, just trying a small test for AnyDSL jit compilation 
(in runtime project). But, I was able to track down all config headers that get generated and copy them.

**Comment by richardmembarth** [comment]
The setup script will setup everything you need to get started.
From there you create your own application using the built components (llvm, thorin, impala | artic, runtime).
For jit, you can have a look at the jit test in Stincilla: https://github.com/AnyDSL/stincilla/tree/master/test

**Comment by m-kurtenacker** [comment]
This issue has been stale for a couple of years; we consider this resolved for the time being.
