### ISSUE TITLE
Q: Compiler error?

### ISSUE THREAD

**Issue by ib00** [AnyDSL/anydsl#16]
I am trying again to compile AnyDSL from scratch. I get the following error:

/tmp/anydsl/runtime/src/cuda_platform.cpp:454:14: error: ‘class llvm::TargetMachine’ has no member named ‘adjustPassManager’
  454 |     machine->adjustPassManager(builder);

The error happens regardless whether I have 'NVPTX' target or not.

**Comment by richardmembarth** [comment]
Are you using/linking the correct LLVM version (14.x), the one build by the setup script?

**Comment by ib00** [comment]
Yes, I did a clean checkout using the script and followed instructions.
So, it's clean checkout and clean build. The only thing I changed 
was this in config:
: ${LLVM_TARGETS:="AArch64;X86"}

**Comment by richardmembarth** [comment]
Can you double check which llvm directory is included during compilation?
```bash
make VERBOSE=1
```
`adjustPssManger()` is defined in `include/llvm/Target/TargetMachine.h`

**Comment by ib00** [comment]
Thanks for suggestion.

I have since resolved the issue. There were two unrelated problems:
1. There were some other LLVM related problems when building in /tmp directory, but not when building in /home. 
2. NVPTX target for LLVM must be enabled otherwise runtime cannot be built

The initial problem reported went away when building everything in /home directory.

**Comment by richardmembarth** [comment]
Yes, you need LLVM to compile the nvptx and amdgpu kernels at runtime.

I will close the issue.
