### ISSUE TITLE
Building rv fails on Linux

### ISSUE THREAD

**Issue by jonas-schmitt** [AnyDSL/anydsl#7]
Hi,
building rv on linux with the setup script currently fails with the following error:
>>> clone cdl-saarland/rv
git clone --recursive git@github.com:cdl-saarland/rv.git
Cloning into 'rv'...
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:10 (message):
  LLVM_INSTALL_ROOT () is not a valid LLVM installation.
-- Configuring incomplete, errors occurred!

**Comment by richardmembarth** [comment]
rv defaults to LLVM 4.0 now.

Can you pull the AnyDSL/anydsl repo and try again?

**Comment by jonas-schmitt** [comment]
Works now. Thanks!

**Comment by leissa** [comment]
actually re-firing the script should suffice as the script automagically updates itself.
