### ISSUE TITLE
latest setup script fails with "unbound variable" error message

### ISSUE THREAD

**Issue by muellan** [AnyDSL/anydsl#9]
I tried to build AnyDSL on a freshly cloned repo and got this:

./setup.sh: line 76: LLVM_TARGETS: unbound variable

Any idea what its value should be?

**Comment by richardmembarth** [comment]
You need to update your ```config.sh``` according to ```config.sh.template```.
We've added ```LLVM_TARGETS``` there.

**Comment by muellan** [comment]
Ah, thanks. I totally forgot that I just copied the old one over.
